[package]
name = "simulator"
version = "0.1.0"
edition = "2021"

[dependencies]
candidate-selection = { path = "../candidate-selection" }
indexer-selection = { path = "../indexer-selection" }
rand = "0.8.5"
thegraph-core = "0.3.0"
