[package]
name = "candidate-selection"
version = "0.1.0"
edition = "2021"

[dependencies]
arrayvec = "0.7.4"
ordered-float = { version = "4.2.0", default-features = false }

[dev-dependencies]
proptest = "1.4.0"
