[package]
name = "indexer-selection"
version = "0.1.0"
edition = "2021"

[dependencies]
candidate-selection = { path = "../candidate-selection" }
custom_debug = "0.6.1"
permutation = "0.4.1"
thegraph-core = "0.5.0"
url = "2.5.0"

[dev-dependencies]
proptest = "1.4.0"
