[package]
name = "indexer-selection"
version = "0.1.0"
edition = "2021"

[dependencies]
candidate-selection = { path = "../candidate-selection" }
permutation = "0.4.1"

[dev-dependencies]
alloy-primitives = "0.7"
proptest = "1.4.0"
